# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fddad2502376ccfb592d40fb7cd285b5156ea58b44c004351bb66923af340f88ef337e6ec4554aa3eaed7c4e19f36badbacd255992d7b62a42fc89ce9858b314

test:
  secret_key_base: 89006882944f4abf5a69a1fe0ec7c19593c13a5d79fc26c290e85dd9bca49bb44431b431f35e07edec3cd0ec479b257c9b82777265d48a6011ffb3d3a2051243

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
